### ISSUE TITLE
cannot install plugin

### ISSUE THREAD

**Issue by ecodiv** [rduivenvoorde/featuregridcreator#10]
On Windows 10, QGIS 3.14 (installed using the stand-alone installer) installing the plugin yields the following error message:

Couldn't load plugin 'FeatureGridCreator' due to an error when calling its classFactory() method 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/brp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FeatureGridCreator\__init__.py", line 43, in classFactory
    from .grid_creator import FeatureGridCreator
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/brp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FeatureGridCreator\grid_creator.py", line 74, in 
    from grid_creator_dialog import FeatureGridCreatorDialog
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\brp\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\FeatureGridCreator\grid_creator_dialog.py", line 30, in 
    os.path.dirname(__file__), 'grid_creator_dialog_base.ui'))
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\PyQt5\uic\__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 142, in 
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/brp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources_rc.py", line 1251, in 
    qInitResources()
  File "C:/Users/brp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources_rc.py", line 1243, in qInitResources
    qt_resource_name, qt_resource_data)
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.15-Pi Pi, d5114d2cfa

**Comment by rduivenvoorde** [comment]
Mmm, thanks for letting me know. I will have a look.

It should indeed already be updated for QGIS3/Py3, but maybe I overlooked something, OR one of the older ui/rc xml files now play up..

**Comment by rduivenvoorde** [comment]
@ecodiv I cannot reproduce here, can you maybe test in a clean profile?
Looking into your stacktrace above, the actual error actually seems to come from QGIS2Web plugin?:
"C:/Users/brp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources_rc.py"

I know there has been some issues recently about python loading paths. Do you have most recent 3.14?
My 'underbelly' ( yes we have that here in NL: onderbuik ;-) ) says that there is maybe an old version of some resources file going around in your profile.... But please let me know if this issue still pops up in a fresh profile, then we have to dig further...

**Comment by ecodiv** [comment]
@rduivenvoorde, you were right, some left-over files in my profile. Should have checked that before, sorry. With a new profile, I can install the plugin without problem. Je onderbuik gevoel klopte :-). Groetjes, Paulo
